name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: run single script
      run: echo hello,world!
    - name: run multiline script
      run: |
           echo this is a multi line script
           echo multi line script works
    - name: work with varialbes
      env:
        FIRST_NAME: "foo"
        LAST_NAME: "bar"
        MSG: "hello,world"
      run: |
        echo ${FISRT_NAME} $LAST_NAME $MSG works!
        
