name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: switch branch to latest release
      env:
        tag_name: ${{secrets.TAG_NAME}}
      run: |
        git checkout -b installme $tag_name
        mkdir artifact
        npm run compile
        npm run gulp vsix:offline:package
        cp *.vsix ./artifact/
    - uses: actions/upload-artifact@master
      with: 
        name: artifact
        path: artifact
        
        
